
all :


stretched.list :
	./gdrive-linux-x64 list --no-header -m 1000 --query "'1R8VuEuiK3v9HLXmnBzYGdHSUFcR5wTZK' in parents" > stretched.list

relaxed.list :
	./gdrive-linux-x64 list --no-header -m 1000 --query "'1FMwaVcfr_RN8J2lZSaw9dL3aTdHTbRpU' in parents" > relaxed.list
